development:
  adapter: mysql2
  encoding: utf8
  database: competitions_development
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  database: competitions_test
  pool: 5
  username: root
  host: <%= ENV['DB_HOST'] || 'localhost' %>

production:
  adapter: mysql2
  encoding: utf8
  database: competitions_production
  pool: 5
  username: root
