development:
  adapter: postgresql
  encoding: unicode
  database: competitions_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: competitions_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: competitions_production
  pool: 5
